### PR TITLE
貢献ポリシーの更新 (MTEngineUpdate)

### PR DESCRIPTION
**Pull request by matarillo**
At [microsoft/Localization wiki](https://github.com/microsoft/Localization/wiki):

> In an effort to improve the quality of MT content, we are transitioning to a neural engine, we believe will provide better translations. Contributions to MT content will be _temporarily_ disabled. Read the changes [here](https://github.com/microsoft/Localization/wiki/MTEngineUpdate)

### CODE REVIEW

**Comment by matarillo** [comment]
@srvbpigh @CeciAc @JasonCard ?

**Comment by v-radelg** [comment]
@matarillo :

Your contribution is still under discussion, we will update you with the decision shortly.  
		 
Thanks for your support, 
 
Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
@matarillo Thank you for your suggestion and translation.
Even if we accept this PR, the changes would be lost if English version is updated.
We also slightly updated the message in Localization Wiki.
So I'll work with English content team if we can get a token added for this message to be in localized version only.
I've assigned this PR to me for now for tracking and will update.
cc @v-radelg

**Comment by JasonCard** [comment]
This change has been [committed](https://github.com/dotnet/docs/commit/b369fd7469dac203a648db285ede1bcb0d44577f) to English version, so it just needs to be translated. However, dotnet loc repos are currently going through a tooling migration, so it may take a couple of weeks for this translation to be ready.

**Comment by matarillo** [comment]
you can just reject this PR once the committed change is translated.

**Comment by JasonCard** [comment]
@matarillo Thank you again for your suggestion. The update in [CONTRIBUTING.md](https://github.com/dotnet/docs.ja-jp/blob/live/CONTRIBUTING.md) is now localized.

**Pull request closed without merging**
