### PR TITLE
Retranslated Focus Overview

### PR DESCRIPTION
**Pull request by terasato**
Now we can understand it.

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @terasato  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hello, @terasato  ,  Thank you for your feedback and suggestion. 

The English source file has been updated recently. Feel free to make new suggestions on the latest version.

Many thanks for your contribution.  

Kind regards,  Microsoft C&E Localization Team

**Comment by terasato** [comment]
The recent changes in English source file does not seems to affect the translation. Do I need to post this issue again?

**Comment by v-radelg** [comment]
@terasato Yes, please generate a new PR

Kind regards, Microsoft C&E Localization Team

**Pull request closed without merging**
