### PR TITLE
Translate "development scenario" link to valid.

### PR DESCRIPTION
**Pull request by kekyo**

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/docker/building-net-docker-images.md](https://github.com/kekyo/docs.ja-jp/blob/docker-dev-scenario-fix/docs/core/docker/building-net-docker-images.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/dotnet-new/articles/core/docker/building-net-docker-images?branch=pr-ja-jp-22) | [Details](#user-content-docs%2Fcore%2Fdocker%2Fbuilding-net-docker-images.md)

<a name="docs%2Fcore%2Fdocker%2Fbuilding-net-docker-images.md"></a>
### [docs/core/docker/building-net-docker-images.md](https://github.com/kekyo/docs.ja-jp/blob/docker-dev-scenario-fix/docs/core/docker/building-net-docker-images.md)
 - **Line 197**: **[Warning]** Invalid file link:(~/docs/core/docker/media/building-net-docker-images/debugging_debugicon.png).
 - **Line 201**: **[Warning]** Invalid file link:(~/docs/core/docker/media/building-net-docker-images/docker-tools-vscode-f5.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C25%5C717bfbe8-2948-11bd-fce9-ff715c4e9a59%5CPullRequest%5C201705250136499429-22%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kekyo** [comment]
Do I have to fix these warnings? I didn't change these links.

**Comment by v-radelg** [comment]
Hi @kekyo , we are still in discussing, will update the decision later soon. 

No, you don't have to fix those.
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@kekyo : Thank you for your feedback and suggestion! 
		
The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Pull request merged**
