### PR TITLE
Fixing link labels

### PR DESCRIPTION
**Pull request by terasato**
I noticed that a lot of link labels are left unchanged after the title of the destination (of the link) article have been modified. So I built [this tool](https://github.com/terasato/LinkLabelChecker) and checked.

I checked the differences one by one since some link labels seem to be intentionally different from the article title.

There are tons of labels left to be fixed, so I hope you take over this issue. If there are anything I can do, please let me know.

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @terasato  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by JasonCard** [comment]
Hi @mairaw, our contributor @terasato has kindly built [this tool](https://github.com/terasato/LinkLabelChecker) to find inconsistencies between link title and actual title in linked URL. He has run this tool for Japanese articles, reviewed results, and opened PRs.
However, since we are translating according to source text, we should not update translation of link title unless it's source is updated. Once link title in source is updated, our localization workflow will update the translation accordingly. So I was wondering if this contributor's tool will be useful for English content to review and update English content?
cc @v-radelg

**Comment by terasato** [comment]
@JasonCard I'd like to point out that many link titles are left unchanged after the translation of the destination article title changed (improved). In this case, you should update link title even if the English text be not changed.

**Comment by terasato** [comment]
I reverted some unimportant changes for clarify the point.

**Comment by JasonCard** [comment]
Hi @terasato, 
Thank you for your additional feedback. 
Yes, that is a known issue where we are currenlty not updating translation of link titles even after translated title of linked article is improved. We are currently not reviewing recycled translation if there is no source update. Your tool maybe helpful in reviewing these cases.
We will take a look into your changes and get back to you.   

Kind regards, 
Microsoft C&E Localization Team
cc @mairaw @v-radelg

**Comment by mairaw** [comment]
It could be interesting to see the results of running this tool. I think in some cases the title is by design different.

**Comment by v-radelg** [comment]
@terasato :
Thank you for your feedback and suggestion!
We agree with your suggestions, and we will include them into the next article update release.
Thank you for your time and support. 
Microsoft C&E Localization Team

**Comment by JasonCard** [comment]
Hi @terasato,
I would also like to let you know that we will be taking a closer look into using the tool you built to review these cases and fixing them for rest of this repo and others. However, it may take some time, so I would like to ask for your patience on this. We will let you know if we run into any questions with your tool. Thank you again for your feedback, building and sharing your tool!

Kind regards,
Microsoft C&E Localization Team
cc @mairaw @v-radelg

**Pull request merged**
