### PR TITLE
Fix a mistranslation in enum.md.

### PR DESCRIPTION
**Pull request by masaniwasdp**

### CODE REVIEW

**Comment by mauriciomoravia** [comment]
Hi @masaniwasdp , we are still in discussing, will update the decision later soon. 

Thanks for your support,
Microsoft C&E Localization Team

**Comment by mauriciomoravia** [comment]
@masaniwasdp  Thank you for your feedback and suggestion! 

We found that this issue is about the translation itself and not aboot the source text. , I am closing this PR. 

Microsoft C&E Localization Team

**Comment by mauriciomoravia** [comment]
@masaniwasdp  Thank you for your feedback and suggestion! 

We found that this issue is about the translation itself and not about the source text, I am closing this PR. 

Microsoft C&E Localization Team

**Comment by masaniwasdp** [comment]
Did you say, "Read the original document"?

**Comment by v-radelg** [comment]
@masaniwasdp , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
