### PR TITLE
Identifier "Object" should not be translated.

### PR DESCRIPTION
**Pull request by y121516**
The "Object" is an identifier, it should be written as "Object".

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/standard/base-types/type-conversion.md](https://github.com/y121516/docs.ja-jp/blob/patch-1/docs/standard/base-types/type-conversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/dotnet/articles/standard/base-types/type-conversion?branch=pr-ja-jp-8) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C21%5C717bfbe8-2948-11bd-fce9-ff715c4e9a59%5CPullRequest%5C201702210209374885-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @y121516 , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by mairaw** [comment]
Most of the xref links should keep the original text. 

/cc @nokura @SonjaSaltzman

**Comment by gosali** [comment]
@y121516 , Thank you for your feedback and suggestion! 
		
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
		
Microsoft C&E Localization Team

**Pull request merged**
