### PR TITLE
Fixed typo in C# and F#.

### PR DESCRIPTION
**Pull request by tanaka-takayoshi**
Can you receive a PR? It's a very simple fix, but the top page is important.

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[index.md](https://github.com/tanaka-takayoshi/docs.ja-jp/blob/patch1/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/dotnet/index?branch=pr-ja-jp-2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C22%5C717bfbe8-2948-11bd-fce9-ff715c4e9a59%5CPullRequest%5C201611221136505546-2%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tanaka-takayoshi** [comment]
I found typo in my PR. I'll make a new PR later.

**Comment by mairaw** [comment]
You don't have to close a PR to make more fixes. You just simply make a new commit to the same branch. For next time 😄

**Comment by tanaka-takayoshi** [comment]
@mairaw Thanks for comment. But I've already make a new PR https://github.com/dotnet/docs.ja-jp/pull/3 Is it OK?

**Comment by mairaw** [comment]
yes, that's totally fine @tanaka-takayoshi. Just thought you'd like to know. I'm talking to the localization team about the PR process.

**Comment by tanaka-takayoshi** [comment]
@mairaw thanks. I'm looking forward to hearing the best way to feedback about localization issue.

**Pull request closed without merging**
